### ISSUE TITLE
Wifi connect icon

### ISSUE THREAD

**Issue by kkanungo17** [catppuccin/kde#1]
Hi,

Is it possible to have a more fitting icon for the connect option in the taskbar? Folder with a globe doesn't seem too appropriate here. Example image is attached.

![Screenshot_20220131_010004](https://user-images.githubusercontent.com/11506039/151714513-c5e37fce-3499-4b87-bb02-7768cf35d0bb.png)

**Comment by Prayag2** [comment]
This theme uses [Papirus Icons](https://github.com/varlesh/papirus-colors) so it's not something we can change. Please report an issue there.
