### ISSUE TITLE
[Feature Request] “Solid” variant with no panel shadow

### ISSUE THREAD

**Issue by onnyyonn** [catppuccin/kde#17]
Currently, the panels have drop shadow and KDE Plasma has no easy way remove them. It would be great if there are “solid” variants for the plasma theme with no drop shadow for panels.

**Comment by Sourcastic** [comment]
Could you attach a picture as to what you mean by shadow?

**Comment by onnyyonn** [comment]
Here is a screenshot with the “Lightly Plasma” Plasma style that comes with Catppuccin. Notice that there is a drop shadow between the panel and the application.
![Screenshot_20221022_003616](https://user-images.githubusercontent.com/963267/197320028-d86bdd89-2c89-4df5-b6f1-beb44b0662f1.png)

As a contrast, here is the Plasma style from “Nordic Solid”, which does not have a shadow and the panel seamlessly blends into the application.
![Screenshot_20221022_003700](https://user-images.githubusercontent.com/963267/197320080-1a04e8da-bc73-4189-bbd2-f14e41114b8d.png)

What I am trying to achive is this seamless blend, when I use Catppuccin KDE and Konsole theme.

**Comment by Sourcastic** [comment]
Thank you for the screenshot, Yeah, we'll try to fix that by moving away from lightly plasma eventually. Right now, there are some licencing issues we need to sort out first. One option is for you specifically is to change the plasma theme until we change the plasma theme we bundle with.

**Comment by Sourcastic** [comment]
But also, I think most plasma styles have a shadow since it's in the default breeze so there's a chance the style we bundle with the theme will end up having it too.

**Comment by onnyyonn** [comment]
I understand the shadow variant being the default option. But are you open to make a solid variant along with it? Only a few background files will be different between those.

**Comment by Sourcastic** [comment]
Yup. I won't be making the plasma style since I have no experience with SVGs, but we can definitely look into it.

**Comment by Cequallium** [comment]
### hey @onnyyonn, an update on this.
For now if you want you can change /home/{USER}/.local/share/plasma/desktoptheme/lightly-plasma-git/widgets/panel-background.svgz with ![panel-background.svgz](https://user-images.githubusercontent.com/85212821/201894362-296607dc-002a-4ff4-ba72-3fadc50c0b3e.png)

**After you download rename it to "panel-background.svgz",**
 Github doesn't allow you to upload .svgz files :p.

As for switching to a different plasma theme, we're considering making modifications to lightly plasma.

**Comment by Sourcastic** [comment]
This was now merged into main and there is no panel shadow, so I'll close the issue.
