### ISSUE TITLE
Menu hover background color clashes with text

### ISSUE THREAD

**Issue by suryaya** [catppuccin/kde#18]
Hi,

Thanks for the nice theme.

There are some contrast issues when I hover my cursor over KDE menus (without clicking anything). This issue goes away if I click a menu item first and _then_ hover my cursor over the other menu items. 

See pics (note - flameshot doesn't capture my cursor):

Dolphin:

![image](https://user-images.githubusercontent.com/59785388/203706203-1a8115a0-8d00-4c54-8356-0e5436e3b998.png)

LO Writer:

![image](https://user-images.githubusercontent.com/59785388/203705910-9687c42c-f234-45ee-9990-97d3c48fc3d4.png)

**Comment by Sourcastic** [comment]
Hi, thanks for the issue.

We can fix this by making the hover colour something like, say, surface0 or perhaps overlay0. A problem I've noticed though is that if you change your accent colour, it changes the hover colour as well and that is unfixable unless you go through and change every instance of flamingo manually. But being readable, at least in the base theme, is good.

So, I guess, changing it to a different colour would fix your issue?

P.S it's mostly personal preference, but KDE's own screenshot tool (spectacle) can capture your cursor.

**Comment by Sourcastic** [comment]
Hi, I've pushed a change that changed the hover colour to surface0. Do tell me how you like it, and text should be a little more readable now.
Here's a screenshot:
![image](https://user-images.githubusercontent.com/79325941/203831030-a5bbcade-670c-4708-8301-24451ee67b34.png)

Do let me know what you think so we can close the issue!

**Comment by suryaya** [comment]
Thanks, that looks much better! Really appreciate your hard work.
