### ISSUE TITLE
Other accent colors

### ISSUE THREAD

**Issue by D3SOX** [catppuccin/kde#2]
Just like with [papirus-folders](https://github.com/catppuccin/papirus-folders) it would be nice if there were KDE colors with different accents.

**Comment by TGRush** [comment]
KDE Plasma already allows for custom accent colors.

**Comment by D3SOX** [comment]
I know but it's not as good as an official version with for the different Catppuccin variants

**Comment by D3SOX** [comment]
Fixed with #8
