### ISSUE TITLE
Upload to the KDE Store

### ISSUE THREAD

**Issue by NNBnh** [catppuccin/kde#23]
As the title suggest. This will make installing the theme way more convenient.

**Comment by Sourcastic** [comment]
Hi, the colour scheme itself is actually on the KDE Store. You can check it out from [here](https://www.pling.com/u/catppuccin/). Or off course, you can do so from the system settings too. As for the global theme, we don't have any other components quite yet, once we have window decoration and/or plasma theme, we'll upload that too.

**Comment by Sourcastic** [comment]
I think it might be best to close this issue for now, as the theme, in its current state, is on the KDE Store.
