### ISSUE TITLE
Create release tag

### ISSUE THREAD

**Issue by michaelBelsanti** [catppuccin/kde#24]
This repo seems to be in a stable state, and having a tagged release makes it simpler to package this theme.

**Comment by Sourcastic** [comment]
Fair enough, we can start making releases whenever it's convenient. The first one will probably be whenever the dev branch is merged in. Wonder what we'd number the first release though, since the theme's already pretty developed.

**Comment by Sourcastic** [comment]
The first release has been created and more will be created from here on out. Thank you for the suggestion!
