### ISSUE TITLE
Window decorations [feature]

### ISSUE THREAD

**Issue by bluebyt65** [catppuccin/kde#4]
I wish a Window decoration theme will be add like Gnome.
![gnome_catppuccin](https://user-images.githubusercontent.com/18442224/180003577-c637868f-dc91-426b-938c-fb430f533d1b.png)

**Comment by laurentlbm** [comment]
I copied and tweaked the window decorations from [Colloid-kde](https://github.com/vinceliuice/Colloid-kde). I changed the colors for the background and the close/minimize/maximize buttons to match the GTK theme (Mocha variant).

You can use it if you want: https://github.com/laurentlbm/dotfiles/tree/main/.local/share/aurorae/themes/Catppuccin-Mocha

**Comment by bluebyt65** [comment]
Thanks! I will try it later!

**Comment by danielgafni** [comment]
+1 this would be cool to have in the KDE store

**Comment by Sourcastic** [comment]
This has now been added, so I'll close this issue. We'll upload to KDE Store soon-ish.
