### ISSUE TITLE
How to uninstall a theme?

### ISSUE THREAD

**Issue by waffleboi9000** [catppuccin/kde#44]
I specifically have the mocha-rosewater variant installed and would like to remove it. (installed using install.sh)

**Comment by justTOBBI** [comment]
You can remove the theme via the Appearance Settings.

**Comment by waffleboi9000** [comment]
I specifically want to remove the window decorations for the gtk theme, or at least revert them back to breeze, because right now they are oversized, even when changing the gtk theme to breeze from the appearance settings
Header of lutris:
![image](https://user-images.githubusercontent.com/89646595/233087650-dc5b16b4-52ed-414d-9481-e6fb448ec575.png)
header of a qt app:
![image](https://user-images.githubusercontent.com/89646595/233087849-6acb87b5-41e5-4e3f-a0d6-c191cac11be8.png)

**Comment by Sourcastic** [comment]
I don't think this is because of the app and/or GTK headers being big in general, rather than the catppuccin theme. Though if you want to remove the catppuccin window decoration theme, you can delete the relevant folders from .local/share/aurorae/themes.

**Comment by Sourcastic** [comment]
Right, yeah, I don't think this is something our theme can change. This just seems to be something with GTK or the app then. GTK headerbars have the extra space to fit the other elements like the searchbar or the hamburger menu I assume.

**Comment by waffleboi9000** [comment]
Part of the theme included window decorations, actually. 
![image](https://user-images.githubusercontent.com/89646595/233139022-e263b389-1649-4fe3-b0c1-8800884d73da.png)
Here's another screenshot that might make it a bit clearer what the issue is:
![image](https://user-images.githubusercontent.com/89646595/233135026-c4f2a7cc-8c11-4e7d-b09f-fbf17b58b1bc.png)
The titlebar buttons are all larger and fuzzy looking.
When I change the application style for gtk apps to adw-gtk3-dark:
![image](https://user-images.githubusercontent.com/89646595/233135422-1a2bbcd1-82dc-45a9-a8a0-697e1c42ad38.png)
It seems like the installation somehow modified the default breeze gtk theme's titlebar buttons, and I'd like to change it back to the default breeze theme with the unmodified titlebar buttons.

**Comment by waffleboi9000** [comment]
Ok so I installed the breeze-gtk theme by simonizor and applied the included Breeze-dark-gtk theme, which has the correct sized icons, but for whatever reason, the autogenerated Breeze gtk theme included in plasma has the large icons.
Breeze-dark-gtk theme:
![image](https://user-images.githubusercontent.com/89646595/233152476-df215630-13a3-424d-a55c-ee26d446aead.png)
Default breeze theme with whatever is going on with it:
![image](https://user-images.githubusercontent.com/89646595/233152611-d8b5c82a-3023-4578-bf56-2c5e9a9b89f2.png)

**Comment by Sourcastic** [comment]
Ah, I think I see the issue: The "breeze" theme when you choose the GTK theme just applies the current plasma theme, as opposed to the same gray-ish breeze theme you'd choose in the appearance settings. As for why it's big and fuzzy, I'm not sure. Maybe because our theme is kind of large too, it tries to do that to GTK?

**Comment by Cequallium** [comment]
Try cleaning your .cache

**Comment by waffleboi9000** [comment]
Tried clearing .cache, no dice.

**Comment by waffleboi9000** [comment]
Just reinstalled my distro, turns out that it's an issue unrelated to the catpuccin theme. Thanks for helping, marking as closed.
