### ISSUE TITLE
Mention dependency on wget and unzip.

### ISSUE THREAD

**Issue by breuxi** [catppuccin/kde#53]
Greetings,

thank you for creating this beautiful theme and convenient installer! Sadly I had a problem using it,  because my machine was missing the unzip package, so the script could not extract some of the contents. By looking at the scripts source, I also saw that wget is used. I know that most linux distros should be shipping these packages by default, but some do not, so in my opinion it would be nice to have it mentioned in the install section of the Readme or have the script check for their presence and exit or output a warning if it fails to find them.

I know that this is probably just a convenience thing, but it could spare somebody the debugging effort and would not be too difficult to implement.

I would also be willing to submit a pr for such behavior if needed! :)

Have a nice day everyone,
Breuxi

**Comment by backwardspy** [comment]
seems like a good idea to me, feel free to submit a PR!

**Comment by Sourcastic** [comment]
Hey, I've just pushed a fix for this. If I uninstall wget or unzip or a few other commands, it does now exit the script and output an error message.

Tysm for raising the issue.
