### ISSUE TITLE
[Bug] Library import requires a version (Splash Screen)

### ISSUE THREAD

**Issue by Zombiefleischer** [catppuccin/kde#63]
I get this weird error, when trying to preview (and when I log in) the splash screen:
```
Failed to show the splash screen preview.
"file:///home/zombiefleischer/.local/share/plasma/look-and-feel/Catppuccin-Mocha-Sapphire/contents/splash/Splash.qml" 
 "Error loading QML file.\nLibrary import requires a version\n"
24 -- exe=/usr/bin/ksplashqml
13 -- platform=xcb
11 -- display=:0
19 -- appname=ksplashqml
17 -- apppath=/usr/bin
10 -- signal=11
10 -- pid=11372
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = ksplashqml path = /usr/bin pid = 11372
KCrash: Arguments: /usr/bin/ksplashqml Catppuccin-Mocha-Sapphire --test 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/ContextDrawer.qml:132:9: QML ListView: Binding loop detected for property "topMargin"
org.kde.drkonqi.bugzilla: RuntimeException: "Failed to resolve bugzilla product"
org.kde.drkonqi: "Failed to resolve bugzilla product"
Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
kf.sonnet.clients.hspell: HSpellDict::HSpellDict: Init failed
qml: 1
qml: 2
qml: state
qml: 1
qml: usefulness
qml: 1
qml: 4
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
/tmp/drkonqi.Reguwf:2: Error in sourced command file:
/usr/share/drkonqi/gdb/preamble.py:4: Error in sourced command file:
Undefined command: "from".  Try "help".
qml: 2
qml: 2
qml: state
qml: 2
Unable to start Dr. Konqi
Re-raising signal for core dump handling.
```
My System (from neofetch):
OS: Debian GNU/Linux 12 (bookworm) x86_64
DE: Plasma 5.27.5
Kernel: 6.1.0-18-amd64

**Comment by Sourcastic** [comment]
Hmm, since you're on plasma 5, did you run the install script from the last plasma-5-compatible commit? I.e run `git checkout v0.2.5` before running `./install.sh` ?

**Comment by Zombiefleischer** [comment]
Okay, switching the branch needs the full repo (at least for me with `--depth=1` it didn't work. But still I get the first 3 lines of the error. I try to restart my pc and see if it's any different.

**Comment by Sourcastic** [comment]
Try also deleting whatever flavour and accent you installed in ``~/.local/share/plasma/look-and-feel`` so you can install it from scratch. Also, no, I don't think adding a depth flag would work in this case, unfortunately.

**Comment by Zombiefleischer** [comment]
So after some removing and cleaning of files, installing and restarting, it now works! Thanks for your time and sorry to bother you :smile:

**Comment by Sourcastic** [comment]
No problem at all! Happy to help.
