### ISSUE TITLE
Gray border line appeard after a transparent terminal goes full screen.

### ISSUE THREAD

**Issue by kzlouge** [catppuccin/kde#65]
### Version:
catppuccin/kde version: v0.2.6
KDE Plasma version: 6.0.3

### Extension may have a bug:
Plasma Window Decorations of Catppuccin 

### Steps to reproduce:
Using _Window Decorations of Catppuccin_ (I tried both _Catppuccin Latte Modern_ and _Catppucin Mocha Classic_).
Set terminal (I tried both the _konsole_ and _alacritty_) transparent.

Then is a gray border line appeared in the top right after the terminal goes full screen.
No gray line If just maximize the terminal.

With _Window Decorations of Catppuccin_ before get konsole full screen:
![1](https://github.com/catppuccin/kde/assets/165113627/a3370eed-ffdb-4388-99a7-5063430ae6d8)

After full screen:
![2](https://github.com/catppuccin/kde/assets/165113627/42f96084-c8ed-444a-b28e-fd9791235de6)

Change the Window Decorations to the default Breeze theme will not have this issue.

### Expected Behavior:
There should not have a gray border line left after full screen.
With the default Window Decorations of Breeze:
![3](https://github.com/catppuccin/kde/assets/165113627/6c1aaa8c-2d37-4604-ab52-92c9fd4a356a)

**Comment by Sourcastic** [comment]
This could have something to do with aurorae themes in general (breeze isn't an aurorae theme) and the transparent windows. Does this persist with other aurorae themes. You seem to have "nothing" and "kde-story-blue" installed, maybe you could try those?

I can't really recreate this though, unfortunately... maybe wayland/xorg has something to do with it too?


![image](https://github.com/catppuccin/kde/assets/79325941/c3105046-35ad-41ca-970b-a8a42beae8fb)

**Comment by kzlouge** [comment]
Thanks for reply.
I just find the window decorations of other themes have the same problem, except for the few themes that come with KDE initially.
I guess the problem is not in the theme. Maybe I should check my wayland or other settings.
Anyway, thanks for the reminder,  I should check more carefully before open a issue.
